name: Dump

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  main:
    name: Dump
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        run: echo $Test
        env:
          TEST: ${{ toJson(github) }}
