name: Test

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: NuGet Login
        uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544 # v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
