name: Test2

on:
  workflow_dispatch:

permissions: {}

jobs:
  check:
    name: Test2
    runs-on: ubuntu-latest

    outputs:
      projects: ${{ steps.x.outputs.projects }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: x
        run: |
          echo 'projects={"include":[{"project":"GitHubSettingsSync","os":"win10","architecture":"x64"},{"project":"GitHubSettingsSync","os":"win10","architecture":"arm64"},{"project":"GitHubSettingsSync","os":"linux","architecture":"x64"},{"project":"GitHubSettingsSync","os":"osx","architecture":"x64"}]}' >> $GITHUB_OUTPUT

  main:
    name: Main
    needs: check

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.check.outputs.projects) }}

    uses: finphie/Actions/.github/workflows/upload-artifacts-dotnet.yml@202302111522
