name: Test2

on:
  workflow_dispatch:

permissions: {}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub repositories
        id: get-github-repositories
        uses: finphie/Actions/.github/actions/get-github-repositories@main
        with:
          archived: false
          fork: false
          language: ''
          limit: 1000
          no-archived: false
          source: false
          visibility: public
          exclude: ''
          json: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo '${{ steps.get-github-repositories.outputs.repositories }}'

      - run: |
          gh api "users/{owner}/repos"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
