name: Test2

on:
  workflow_dispatch:

permissions: {}

jobs:
  check:
    name: Test2
    runs-on: ubuntu-latest

    outputs:
      projects: ${{ steps.x.outputs.projects }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: x
        run: |
          echo 'projects={"include":[{"project":"GitHubSettingsSync","os":"win10","architecture":"x64"},{"project":"GitHubSettingsSync","os":"win10","architecture":"arm64"},{"project":"GitHubSettingsSync","os":"linux","architecture":"x64"},{"project":"GitHubSettingsSync","os":"osx","architecture":"x64"}]}' >> $GITHUB_OUTPUT

  main:
    name: Main
    needs: check

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.check.outputs.projects) }}

    uses: finphie/Actions/.github/workflows/upload-artifacts-dotnet.yml@202302111522
    with:
      project: ${{ matrix.project }}
      target-platform-identifier: ${{ matrix.target-platform-identifier != '' && matrix.target-platform-identifier || 'none' }}
      target-platform-version: ${{ matrix.target-platform-version }}
      os: ${{ matrix.os }}
      architecture: ${{ matrix.architecture }}
      workload-restore: ${{ matrix.workload-restore }}
      version: v0.1.0
      suffix: "\
        ${{ (startsWith(matrix.os, 'win') && 'windows') || (startsWith(matrix.os, 'osx') && 'macos') || 'linux' }}_\
        test_\
        ${{ matrix.architecture }}"
