name: Test2

on:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        if: github.ref_name == 'main'
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Checkout repository
        if: github.ref_name != 'main'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: |
          touch test.txt

      - name: Create pull request
        uses: finphie/Actions/.github/actions/create-pull-request@main
        with:
          path: ${{ github.workspace }}
          commit-message: Commit message
          branch: create-pull-request
          labels: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
