name: Test

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: finphie/Actions/.github/actions/test@test
        with:
          nuget-user: ${{ secrets.NUGET_USER }}
