name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo 'a' > a.txt
          echo 'b' > b.txt

      - uses: actions/upload-artifact@v3
        with:
          name: test1
          path: a.txt
          retention-days: 1

      - uses: actions/upload-artifact@v3
        with:
          name: test2
          path: b.txt
          retention-days: 1

  main:
    name: Main
    needs: upload
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v3

      - name: Compress archive
        uses: finphie/Actions/.github/actions/compress-archive@202302011234
        with:
          path: ${{ steps.download.outputs.download-path }}
          destination-path: ${{ runner.temp }}
          root: false

      - name: Upload release assets
        uses: finphie/Actions/.github/actions/upload-release-assets@main
        with:
          tag: v0.1.0
          files: |
            ${{ runner.temp }}/*.zip
